// Textos dos arquivos gerados. Ficam aqui, e não nos JSON de src/i18n, porque quem
// escreve o Excel e o PDF é o servidor - carregar os locales do cliente traria as
// centenas de chaves da interface para dentro de um módulo que precisa de trinta.
// O idioma vem do cliente na requisição; o padrão é pt, o mesmo fallback do app.

const PT = {
  relatorio: "Relatório de tarefas",
  resumo: "Resumo",
  empresa: "Empresa",
  geradoEm: "Gerado em",
  escopo: "Escopo",
  todosOsQuadros: "Todos os quadros",
  responsavel: "Responsável",
  responsaveis: "Responsáveis",
  todosOsResponsaveis: "Todos os responsáveis",
  semResponsavel: "Sem responsável",
  status: "Situação",
  statusTodos: "Todas as tarefas",
  statusPendentes: "Somente pendentes",
  statusConcluidos: "Somente concluídas",
  // KPIs
  total: "Tarefas",
  concluidos: "Concluídas",
  pendentes: "Pendentes",
  atrasados: "Atrasadas",
  semPrazo: "Sem prazo",
  urgentes: "Urgentes",
  importantes: "Importantes",
  comAnexo: "Com anexo",
  taxaConclusao: "Conclusão",
  checklist: "Checklist",
  // Colunas da tabela
  colId: "ID do cartão",
  colTitulo: "Tarefa",
  colQuadro: "Quadro",
  colColuna: "Coluna",
  colCriacao: "Criado em",
  colConclusao: "Concluído em",
  colResponsaveis: "Responsáveis",
  colInicio: "Início",
  colPrazo: "Prazo",
  colSituacao: "Situação",
  colPrioridade: "Prioridade",
  colEtiquetas: "Etiquetas",
  colChecklist: "Checklist",
  colAnexos: "Anexos",
  colLocal: "Local",
  // Valores
  feito: "Concluída",
  aFazer: "Pendente",
  atrasada: "Atrasada",
  urgente: "Urgente",
  importante: "Importante",
  porQuadro: "Distribuição por quadro",
  porResponsavel: "Distribuição por responsável",
  semTarefas: "Nenhuma tarefa para os filtros escolhidos.",
  pagina: "Página",
  de: "de",
  etiquetas: { gray: "Cinza", blue: "Azul", green: "Verde", amber: "Âmbar", red: "Vermelho", purple: "Roxo" },
};

const EN = {
  relatorio: "Task report",
  resumo: "Summary",
  empresa: "Company",
  geradoEm: "Generated on",
  escopo: "Scope",
  todosOsQuadros: "All boards",
  responsavel: "Assignee",
  responsaveis: "Assignees",
  todosOsResponsaveis: "All assignees",
  semResponsavel: "Unassigned",
  status: "Status",
  statusTodos: "All tasks",
  statusPendentes: "Pending only",
  statusConcluidos: "Completed only",
  total: "Tasks",
  concluidos: "Completed",
  pendentes: "Pending",
  atrasados: "Overdue",
  semPrazo: "No due date",
  urgentes: "Urgent",
  importantes: "Important",
  comAnexo: "With attachment",
  taxaConclusao: "Completion",
  checklist: "Checklist",
  colId: "Card ID",
  colTitulo: "Task",
  colQuadro: "Board",
  colColuna: "List",
  colCriacao: "Created on",
  colConclusao: "Completed on",
  colResponsaveis: "Assignees",
  colInicio: "Start",
  colPrazo: "Due",
  colSituacao: "Status",
  colPrioridade: "Priority",
  colEtiquetas: "Labels",
  colChecklist: "Checklist",
  colAnexos: "Attachments",
  colLocal: "Location",
  feito: "Completed",
  aFazer: "Pending",
  atrasada: "Overdue",
  urgente: "Urgent",
  importante: "Important",
  porQuadro: "Breakdown by board",
  porResponsavel: "Breakdown by assignee",
  semTarefas: "No tasks match the selected filters.",
  pagina: "Page",
  de: "of",
  etiquetas: { gray: "Gray", blue: "Blue", green: "Green", amber: "Amber", red: "Red", purple: "Purple" },
};

const ES = {
  relatorio: "Informe de tareas",
  resumo: "Resumen",
  empresa: "Empresa",
  geradoEm: "Generado el",
  escopo: "Alcance",
  todosOsQuadros: "Todos los tableros",
  responsavel: "Responsable",
  responsaveis: "Responsables",
  todosOsResponsaveis: "Todos los responsables",
  semResponsavel: "Sin responsable",
  status: "Estado",
  statusTodos: "Todas las tareas",
  statusPendentes: "Solo pendientes",
  statusConcluidos: "Solo completadas",
  total: "Tareas",
  concluidos: "Completadas",
  pendentes: "Pendientes",
  atrasados: "Atrasadas",
  semPrazo: "Sin fecha",
  urgentes: "Urgentes",
  importantes: "Importantes",
  comAnexo: "Con adjunto",
  taxaConclusao: "Finalización",
  checklist: "Checklist",
  colId: "ID de la tarjeta",
  colTitulo: "Tarea",
  colQuadro: "Tablero",
  colColuna: "Lista",
  colCriacao: "Creado el",
  colConclusao: "Completado el",
  colResponsaveis: "Responsables",
  colInicio: "Inicio",
  colPrazo: "Fecha límite",
  colSituacao: "Estado",
  colPrioridade: "Prioridad",
  colEtiquetas: "Etiquetas",
  colChecklist: "Checklist",
  colAnexos: "Adjuntos",
  colLocal: "Ubicación",
  feito: "Completada",
  aFazer: "Pendiente",
  atrasada: "Atrasada",
  urgente: "Urgente",
  importante: "Importante",
  porQuadro: "Distribución por tablero",
  porResponsavel: "Distribución por responsable",
  semTarefas: "Ninguna tarea con los filtros elegidos.",
  pagina: "Página",
  de: "de",
  etiquetas: { gray: "Gris", blue: "Azul", green: "Verde", amber: "Ámbar", red: "Rojo", purple: "Morado" },
};

const MAPA = { pt: PT, en: EN, es: ES };

export function rotulos(idioma) {
  return MAPA[idioma] || PT;
}

export function nomeDoStatus(t, status) {
  if (status === "pendentes") return t.statusPendentes;
  if (status === "concluidos") return t.statusConcluidos;
  return t.statusTodos;
}
